Poll/Poll/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('user.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Poll/user/urls.py
from django.urls import path,include
from . import views

urlpatterns=[
    path('',views.index,name="index"),
    path('register/',views.registerUser,name="register"),
    path('login/',views.loginUser,name="login"),
    path('logout/',views.logoutUser,name="logout"),
    path('create/',views.poll_create,name="poll-create"),
    path('detail/<str:pk>/',views.polldetail,name="poll-detail"),
    path('result/<str:pk>/',views.pollresult,name="poll-result"),
]

Poll/user/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.
class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE,null=True,blank=True)
    username=models.CharField(max_length=200,blank=True,null=True)
    def __str__(self):
        return str(self.user.username)

class Poll(models.Model):
    owner= models.ForeignKey(Profile,on_delete=models.CASCADE)
    text=models.TextField()
    publishedAt=models.DateTimeField(default=timezone.now)
    active=models.BooleanField(default=True)
    def __str__(self):
        return str(self.text)
    @property
    def total_vote(self):
        return self.vote_set.count()
    def get_result_dict(self):
        res = []
        for choice in self.choice_set.all():
            d = {}
            d['text'] = choice.choice_value
            d['num_votes'] = choice.total_vote
            if not self.total_vote:
                d['percentage'] = 0
            else:
                d['percentage'] = int((choice.total_vote /
                                   self.total_vote)*100)

            res.append(d)

        return res
    def has_user_vote(self,user):
        owner_votes=user.vote_set.all()
        qs=owner_votes.filter(poll=self)
        if qs.exists():
            return False
        return True

class Choice(models.Model):
    poll= models.ForeignKey(Poll,on_delete=models.CASCADE)
    choice_value=models.CharField(max_length=255)
    @property
    def total_vote(self):
        return self.vote_set.count()

class Vote(models.Model):
    user=models.ForeignKey(Profile,on_delete=models.CASCADE)
    poll = models.ForeignKey(Poll,on_delete=models.CASCADE)
    choices= models.ForeignKey(Choice,on_delete=models.CASCADE)

Poll/user/forms.py
from .models import Poll,Choice
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2']
        
    def __init__(self,*args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args,**kwargs)

        for name,field in self.fields.items():
            field.widget.attrs.update({'class':'form-control'})
class PollAddForm(forms.ModelForm):
    choice1 = forms.CharField(label='Choice 1', max_length=100, min_length=1,
                              widget=forms.TextInput(attrs={'class': 'form-control'}))
    choice2 = forms.CharField(label='Choice 2', max_length=100, min_length=1,
                              widget=forms.TextInput(attrs={'class': 'form-control'}))
    choice3 = forms.CharField(label='Choice 3', max_length=100, min_length=1,
                              widget=forms.TextInput(attrs={'class': 'form-control'}))
    choice4 = forms.CharField(label='Choice 4', max_length=100, min_length=1,
                              widget=forms.TextInput(attrs={'class': 'form-control'}))
    class Meta:
        model = Poll
        fields = ['text', 'choice1', 'choice2','choice3','choice4']
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control', 'rows': 5, 'cols': 20}),
        }

class ChoiceAddForm(forms.ModelForm):
    class Meta:
        model = Choice
        fields = ['choice_value', ]
        widgets = {
            'choice_text': forms.TextInput(attrs={'class': 'form-control', })
        }

Poll/user/views.py
from django.shortcuts import render,redirect
from django.urls import reverse
from django.contrib import messages
from .models import Poll,Choice,Vote
from django.contrib.auth.decorators import login_required
from .forms import PollAddForm,CustomUserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout
# Create your views here.
def logoutUser(request):
    logout(request)
    messages.info(request,'User is logged out')
    return redirect('login')
def loginUser(request):
    if request.user.is_authenticated:
        return redirect('index')
    if request.method=='POST':
        username = request.POST['username'].lower()
        password = request.POST['password']
        
        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request,'User does not exist')

        user= authenticate(request,username=username,password=password)
        if user is not None:
            login(request,user)
            return redirect(request.GET['next'] if 'next' in request.GET else 'index')
        else:
            messages.error(request,'Username or Password is incorrect')
    return render(request,'login_register.html')
def registerUser(request):
    form = CustomUserCreationForm()
    page='register'
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            
            login(request,user)
            messages.success(request,"You login successfully")
            return redirect('index')
        else:
            messages.success(request," An errror occur during register")
    context = {'page':page,'form':form}
    return render(request,'login_register.html',context)

def index(request):
    poll=Poll.objects.all()
    return render(request,'polllist.html',{"polllist":poll})
def poll_create(request):
    if request.method == 'POST':
        form=PollAddForm(request.POST)
        if form.is_valid:
            poll=form.save(commit=False)
            poll.owner= request.user.profile
            poll.save()
            choice1 = Choice(
                    poll=poll, choice_value=form.cleaned_data['choice1']).save()
            choice2 = Choice(
                    poll=poll, choice_value=form.cleaned_data['choice2']).save()
            choice3 = Choice(
                    poll=poll, choice_value=form.cleaned_data['choice3']).save()
            choice3 = Choice(
                    poll=poll, choice_value=form.cleaned_data['choice4']).save()
            return redirect(reverse('poll-detail',args=[poll.id]))

    else:
        form=PollAddForm()
    return render(request,'poll_form.html',{'form':form})


def polldetail(request,pk):
    pollobj=Poll.objects.get(id=pk)
    if not pollobj.has_user_vote(request.user.profile):
        messages.info(request,'You already voted for this poll')
        return redirect("index")
    if request.method == 'POST':
        choice_id = request.POST.get('choice')
        if choice_id:
            choice= Choice.objects.get(id=choice_id)
            vote=Vote(user=request.user.profile,poll=pollobj,choices=choice)
            vote.save()
            return redirect(reverse('poll-result',args=[pollobj.id]))
    return render(request,'polldetail.html',{'pollobj':pollobj})

def pollresult(request,pk):
    pollobj=Poll.objects.get(id=pk)
    return render(request,'pollresult.html',{'pollobj':pollobj})

Poll/templates/header.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
  </head>
  <body>
    {% if messages %} {% for message in messages %}
    <div class="alert popup1 alert--{{message.tags}}">
      <p class="alert__message">{{message}}</p>
      <button class="alert__close">X</button>
    </div>
    {% endfor%} {% endif %} {% block content %} {% endblock content %}
    <script>
      var popupEl = document.querySelector(".popup1");
      var button = document.querySelector(".alert__close");

      button.addEventListener("click", function () {
        popupEl.classList.add("closed");
      });
    </script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

Poll/templates/home.html
{% extends 'header.html' %} {% load static %} {% block content %}
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Poll</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="#">{{request.user}}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'register' %}">Login</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>
{% block maincontent %} {% endblock maincontent %} {% endblock content %}

Poll/templates/login_register.html
{% extends 'home.html' %} {% load static %} {% block maincontent %} {% if page == "register" %}
<style>
  .auth {
    padding: 1rem;
  }
</style>
<div class="auth container">
  <div class="card">
    <div class="card-header text-center">
      <h3>Account SignUp</h3>
    </div>
    <div class="card-body">
      <form method="POST" action="{% url 'register' %}" class="form">
        {% csrf_token %}
        <!-- Input:Text -->
        {% for field in form %}
        <div class="form__field">
          <label for="formInput#text">{{field.label}} </label>
          {{field}}

          <!-- {% if field.help_text %}
        <small>{{field.help_text}}</small>
        {% endif %} -->

          {% for error in field.errors %}
          <p style="color: red">{{error}}</p>
          {% endfor %}
        </div>
        {% endfor %}
        <div class="row mt-3">
          <div class="col-auto">
            <input class="btn btn-primary" type="submit" value="Sign  In" />
          </div>
          <div class="col-auto">
            <a href="{% url 'login' %}" class="btn btn-info">Log In</a>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
{% else %}

<!-- user Login Form-->
<div class="container auth--field">
  <div class="card">
    <div class="card-header text-center">
      <h3>Account Login</h3>
    </div>
    <div class="card-body">
      <form method="POST" action="" class="form auth__form">
        {% csrf_token %}
        <!-- Input:Email -->
        <div class="form__field">
          <label for="formInput#text" class="form-label">Username: </label>
          <input class="form-control" id="formInput#text" type="text" name="username" placeholder="Enter your username..." />
        </div>

        <!-- Input:Password -->
        <div class="form__field">
          <label for="formInput#password" class="form-label">Password: </label>
          <input class="form-control" id="formInput#passowrd" type="password" name="password" placeholder="••••••••" />
        </div>
        <div class="mt-3">
          <input class="btn btn-primary" type="submit" value="Log In" />
        </div>
      </form>
      <div class="row mt-5">
        <div class="col-auto">
          <p>Don’t have an Account? <a href="{% url 'register' %}" class="btn btn-primary">Sign Up</a></p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endif %} {% endblock maincontent %}

Poll/templates/poll_form.html
{% extends 'home.html' %} {% load static %}{% block maincontent %}
<style>
  .container-box {
    padding: 0 10rem;
  }
</style>
<div class="container">
  <h3>Create Poll</h3>
  <div class="container-box">
    <form action="" method="POST">
      {% csrf_token %} {% for field in form %}
      <div class="form-group">{{ field.errors }} {{ field.label_tag }} {{ field }}</div>
      {% endfor %}
      <button type="submit" class="btn btn-primary">Add Poll</button>
      <a class="btn btn-warning" href="{% url 'index' %}" role="button">Back</a>
    </form>
  </div>
</div>
{% endblock maincontent %}

Poll/templates/polldetail.html
{% extends 'home.html' %} {% load static %} {% block maincontent %}
<div class="container">
  <div class="card">
    <div class="card-header">
      <h3>Poll Detail</h3>
    </div>
    <div class="card-body">
      <h6>{{pollobj.text}}</h6>
      <form action="." method="POST">
        {% csrf_token %} {% for choice in pollobj.choice_set.all %}
        <div class="form-check">
          <input type="radio" name="choice" class="form-check-input" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
          <label for="choice{{ forloop.counter }}" class="form-check-label">{{ choice.choice_value }}</label>
        </div>
        {% endfor %}
        <input type="submit" value="Vote" class="btn btn-primary mt-3" />
      </form>
    </div>
  </div>
</div>
{% endblock maincontent %}

Poll/templates/polllist.html
{% extends 'home.html' %} {% load static %}{% block maincontent %}
<style>
  .item-wrap {
    display: flex;
    justify-content: space-between;
  }
</style>
<div class="container">
  <a href="{% url 'poll-create' %}" class="btn btn-primary">CreatePoll</a>
  <div class="card">
    <div class="card-header"><h3>Poll list</h3></div>
    <div class="card-body">
      <div class="poll-listbox">
        {% for poll in polllist %}
        <div class="poll-list">
          {% if poll.active %}
          <div class="item-wrap">
            <a href="{% url 'poll-detail' poll.id %}" class="text-link">{{poll.text}}</a>
            <p>Created by : {{poll.owner.username}}</p>
            <p>Published on : {{poll.publishedAt}}</p>
          </div>
          {% endif %}
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
<div class="container mt-10">
  <div class="card">
    <div class="card-header"><h3>Your Active polls</h3></div>
    <div class="card-body">
      {% if request.user.profile.poll_set.all %}
      <div class="poll-listbox">
        {% for poll in request.user.profile.poll_set.all %}
        <div class="poll-list">
          {% if poll.active %}
          <div class="item-wrap">
            <a href="{% url 'poll-detail' poll.id %}" class="text-link">{{poll.text}}</a>
            <p>Created by : {{poll.owner.username}}</p>
          </div>
          {% endif %}
        </div>
        {% endfor %}
      </div>
      {% else %}
      <h3>No active polls</h3>
      {% endif %}
    </div>
  </div>
</div>
{% endblock maincontent %}

Poll/templates/pollresult.html
{% extends 'home.html' %} {% load static %}{% block maincontent %}
<div class="container">
  <div class="card">
    <div class="card-header">
      <h3>Poll Result</h3>
    </div>
    <div class="card-body">
      <h6>Result for: {{pollobj.text}}</h6>
      <p>Total vote {{pollobj.total_vote}}</p>
      {% for option in pollobj.get_result_dict %}
      <div class="row">
        <div class="col-auto"><p>option {{forloop.counter}} : {{option.text}}</p></div>
        <div class="col progress-bar">
          <div class="progress" role="progressbar" aria-label="Success example" aria-valuenow="{{option.percentage}}" aria-valuemin="0" aria-valuemax="100">
            <div class="progress-bar bg-success" style="width: {{ option.percentage }}%">{{option.percentage}}%</div>
          </div>
        </div>
        <div class="col-auto"><p>Number of Vote:{{option.num_votes}}</p></div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock maincontent %}